name: Restaurants API - CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: publish
        run: dotnet publish ./Restaurants.Api/Restaurants.Api.csproj -o ${{env.DOTNET_ROOT}}/api --no-build 
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: api-artifact
          path: ${{env.DOTNET_ROOT}}/api
        
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a Build Artifact
      - uses: actions/download-artifact@v5.0.0
        with:
          name: api-artifact

      
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v3.0.6
        with:
          app-name: 'restaurantes-api-dev'
          publish-profile: ${{secrets.PUBLISH_PROFILE_DEV}}


  
  
