name: Restaurants API - CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish
        run: dotnet publish ./Restaurants.Api/Restaurants.Api.csproj -c Release -o ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: ./publish
          if-no-files-found: error

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-artifact
          path: ./drop

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: restaurantes-api-dev 
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}
          package: ./drop                   
